//
//  Dream.swift
//  quinielizer
//
//  Created by Matias Mazzei on 1/3/17.
//  Copyright © 2017 mmazzei. All rights reserved.
//

import Foundation

/// Based on http://www.quini-6-resultados.com.ar/significado-suenos.aspx
struct Dream: QuinielaMapping {
    static let meanings = [
        "Huevos",
        "Agua",
        "Niño",
        "San Cono",
        "La Cama",
        "Gato",
        "Perro",
        "Revolver",
        "Incendio",
        "Arroyo",
        "La leche",
        "Palito",
        "Soldado",
        "La yeta",
        "Borracho",
        "Niña bonita",
        "Anillo",
        "Desgracia",
        "Sangre",
        "Pescado",
        "La fiesta",
        "La mujer",
        "El loco",
        "Mariposa",
        "Caballo",
        "Gallina",
        "La misa",
        "El peine",
        "El cerro",
        "San Pedro",
        "Santa Rosa",
        "La luz",
        "Dinero",
        "Cristo",
        "Cabeza",
        "Pajarito",
        "Manteca",
        "Dentista",
        "Aceite",
        "Lluvia",
        "Cura",
        "Cucho",
        "Zapatilla",
        "Balcón",
        "La cárcel",
        "El vino",
        "Tomates",
        "Muerto",
        "Muerto habla",
        "La carne",
        "El pan",
        "Serrucho",
        "Madre",
        "El barco",
        "La vaca",
        "Los gallegos",
        "La caída",
        "Jorabajo",
        "Ahogado",
        "Planta",
        "Virgen",
        "Escopeta",
        "Inundacion",
        "Casamiento",
        "Llanto",
        "Cazador",
        "Lombrices",
        "Víbora",
        "Sobrinos",
        "Vicios",
        "Muerto sueño",
        "Excrementos",
        "Sorpresa",
        "Hospital",
        "Negros",
        "Payaso",
        "Llamas",
        "Las piernas",
        "Ramera",
        "Ladrón",
        "La bocha",
        "Flores",
        "Pelea",
        "Mal tiempo",
        "Iglesia",
        "Linterna",
        "Humo",
        "Piojos",
        "El Papa",
        "La rata",
        "El miedo",
        "Excusado",
        "Médico",
        "Enamorado",
        "Cementerio",
        "Anteojos",
        "Marido",
        "La mesa",
        "Lavandera",
        "Hermanos"
    ]
}
