//
//  Profession.swift
//  quinielizer
//
//  Created by Matias Mazzei on 1/3/17.
//  Copyright © 2017 mmazzei. All rights reserved.
//

import Foundation

/// Based on http://www.quini-6-resultados.com.ar/significado-suenos.aspx
struct Profession: QuinielaMapping {
    static let meanings = [
        "Almacenero",
        "Plomero",
        "Maestro",
        "Artesano",
        "Herrero",
        "Gomero",
        "Veterinario",
        "Policía",
        "Bombero",
        "Diseñador",
        "Repostero",
        "Ferretero",
        "Soldado",
        "Jubilado",
        "Barman",
        "Modista",
        "Secretaria",
        "Chapista",
        "Chofer",
        "Pescado",
        "Bailarina",
        "Ama de Casa",
        "Psicólogo",
        "Cocinero",
        "Jockey",
        "Feriante",
        "Cantante",
        "Peluquero",
        "Astrólogo",
        "Farmacéutico",
        "Planografista",
        "Electricista",
        "Quinielero",
        "Eclesiástico",
        "Contador",
        "Pintor",
        "Transportista",
        "Dentista",
        "Vidriero",
        "Sodero",
        "Profesor",
        "Afilador",
        "Joyero",
        "Ferroviario",
        "Cajero",
        "Portero",
        "Fumigador",
        "Fotógrafo",
        "Vendedor",
        "Carnicero",
        "Panadero",
        "Carpintero",
        "Doméstica",
        "Marinero",
        "Tapicero",
        "Músico",
        "Masajista",
        "Zapatero",
        "Guardavidas",
        "Jardinero",
        "Telefonista",
        "Locutor",
        "Ingeniero",
        "Gráfico",
        "Obrero",
        "Taxista",
        "Agricultor",
        "Político",
        "Librero",
        "Buscavidas",
        "Heladero",
        "Bancario",
        "Diariero",
        "Pedicura",
        "Albañil",
        "Actor",
        "Periodista",
        "Enfermera",
        "Prostituta",
        "Cerrajero",
        "Tornero",
        "Florista",
        "Deportista",
        "Cartero",
        "Arquitecto",
        "Mecánico",
        "Parrillero",
        "Cadete",
        "Sastre",
        "Kiosquero",
        "Fletero",
        "Gasista",
        "Médico",
        "Técnico",
        "Funebrero",
        "Oculista",
        "Empleado",
        "Mozo",
        "Lavandero",
        "Viajante"
    ]
}
